#!/bin/bash

cd "$(dirname "$0")"
# reductions
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/1_out_reduction.jpg nearest_neighbor-200
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/2_out_reduction.jpg bilinear-200
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/3_out_reduction.jpg bicubic-200
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/4_out_reduction.png lanczos-200

#color quant
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/5_out_uniform_8.png nearest_neighbor-200 uniform-8
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/6_out_pop_8.png nearest_neighbor-200 popularity-8
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/7_out_medcut_8.png nearest_neighbor-200 median_cut-8
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/8_out_kmeans_8.png nearest_neighbor-200 kmeans-8
../pixel_art_gen ./demo_assets/girl.jpg ./demo_assets/9_girl_kmeans_8.png median_cut-8

../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/10_out_uniform_27.png nearest_neighbor-200 uniform-27
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/11_out_pop_27.png nearest_neighbor-200 popularity-27
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/12_out_medcut_27.png nearest_neighbor-200 median_cut-27
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/13_out_kmeans_27.png nearest_neighbor-200 kmeans-27

../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/14_out_uniform_64.png nearest_neighbor-200 uniform-64
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/15_out_pop_64.png nearest_neighbor-200 popularity-64
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/16_out_medcut_64.png nearest_neighbor-200 median_cut-64
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/17_out_kmeans_64.png nearest_neighbor-200 kmeans-64

#dithering
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/18_out_bayer_8.png nearest_neighbor-300 bayer
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/19_out_bayer_16.png nearest_neighbor-300 bayer kmeans-16
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/20_out_atkin_8.png nearest_neighbor-300 atkinson
../pixel_art_gen ./demo_assets/demo_1.jpg ./demo_assets/21_out_atkin_16.png nearest_neighbor-300 atkinson kmeans-16

../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/22_lenna_bayer_kmeans.png nearest_neighbor-200 bayer
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/23_lenna_bayer_uniform.png nearest_neighbor-200 bayer uniform-8
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/24_lenna_bayer_pop.png nearest_neighbor-200 bayer popularity-8
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/25_lenna_bayer_medcut.png nearest_neighbor-200 bayer median_cut-8
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/26_lenna_bayer_8_100.png nearest_neighbor-100 bayer

../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/27_lenna_bayer_3.png nearest_neighbor-200 bayer kmeans-3
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/28_lenna_bayer_2.png nearest_neighbor-200 bayer kmeans-2
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/29_lenna_atkin_3.png nearest_neighbor-200 atkinson kmeans-3
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/30_lenna_atkin_2.png nearest_neighbor-200 atkinson kmeans-2
../pixel_art_gen ./demo_assets/lenna.png ./demo_assets/31_lenna_atkin_8.png nearest_neighbor-200 atkinson kmeans-8


../pixel_art_gen ./demo_assets/bw.png ./demo_assets/bw_1_out.png nearest_neighbor-200 bayer kmeans-8
../pixel_art_gen ./demo_assets/bw.png ./demo_assets/bw_2_out.png nearest_neighbor-200 bayer kmeans-2
../pixel_art_gen ./demo_assets/bw.png ./demo_assets/bw_3_out.png nearest_neighbor-200 bayer kmeans-3

../pixel_art_gen ./demo_assets/bw.png ./demo_assets/bw_4_out.png nearest_neighbor-200 atkinson kmeans-8
../pixel_art_gen ./demo_assets/bw.png ./demo_assets/bw_5_out.png nearest_neighbor-250 atkinson kmeans-2
../pixel_art_gen ./demo_assets/bw.png ./demo_assets/bw_6_out.png nearest_neighbor-200 atkinson kmeans-3
